set -g default-terminal "tmux-256color"
set-option -ga terminal-features ",xterm-256color:usstyle"
set-option -sa terminal-features ',xterm-256color:RGB'

# reload config file with prefix + r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable mouse control
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off

# status bar styling
set -g status-style 'fg=colour2 dim'
setw -g window-status-style 'fg=colour2 dim'
setw -g window-status-current-style 'fg=colour5 bold'

# renumber windows after closing one
set -g renumber-windows on

# scrollback history limit
set -g history-limit 10000

# new windows/panes open in current directory
bind c new-window -c "#{pane_current_path}"

# better copy mode key bindings
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# easier pane splitting
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# don't do anything when a bell rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# border colours
set -g pane-border-style "fg=#333333"
set -g pane-active-border-style "bg=default fg=green"

# messages
set -g message-style 'fg=colour5 bold'

# status right
set -g status-right '%A %d/%m/%Y %H:%M | #(curl 192.168.1.137:8000/weather && sleep 60)'
set -g status-right-length 60
set -g status-interval 2

# popups
bind C-f display-popup -d "#{pane_current_path}" -w 80% -h 80% -E "ranger"
bind C-g display-popup -d "#{pane_current_path}" -w 80% -h 80% -E "lazygit"
bind C-s display-popup -d "#{pane_current_path}" -w 80% -h 80% -E "$SHELL"
